language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pygobject
# command to run tests
script:
  - if [[1 == 1]]; echo success; fi
  # - pytest # or py.test for Python versions 3.5 and below
